unscript/mercuri/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name='mercuri'

urlpatterns = [
    path('addPatient', views.addPatient.as_view(), name="addPatient"),
    path('addDoctor', views.addDoctor.as_view(), name="addDoctor"),
    path('addStaff', views.addStaff.as_view(), name="addStaff"),
    path('addReception', views.addReception.as_view(), name="addReception"),
    path('modifyPatient/<str:mail>', views.modifyPatient.as_view(), name="modifyPatient"),
    path('addHospital', views.addHospital.as_view(), name="addHospital"),
    path('InstanceStatus', views.InstanceStatus.as_view(), name="InstanceStatus"),
    path('Dashboard', views.Dashboard.as_view(), name="Dashboard"),
    path('listPatients', views.listPatients.as_view(), name="listPatients"),
    path('modifyHospital', views.modifyHospital.as_view(), name="modifyHospital"),
    path('addHospital', views.addHospital.as_view(), name="addHospital"),
    path('searchPatient', views.searchPatient.as_view(), name="searchPatient"),
]

unscript/unscript/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Login.as_view(), name="login"),
    path('mercuri',include('mercuri.urls')),
    path('logout', views.logout_user, name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

unscript/templates/includes/fixed-plugin.html

  <div class="fixed-plugin">
    <div class="dropdown show-dropdown">
      <a href="#" data-toggle="dropdown">
        <i class="fa fa-cog fa-2x"> </i>
      </a>
      <ul class="dropdown-menu">
        <li class="header-title"> Sidebar Background</li>
        <li class="adjustments-line">
          <a href="javascript:void(0)" class="switch-trigger background-color">
            <div class="badge-colors text-center">
              <span class="badge filter badge-primary active" data-color="primary"></span>
              <span class="badge filter badge-info" data-color="blue"></span>
              <span class="badge filter badge-success" data-color="green"></span>
            </div>
            <div class="clearfix"></div>
          </a>
        </li>
        <li class="adjustments-line text-center color-change">
          <span class="color-label">LIGHT MODE</span>
          <span class="badge light-badge mr-2"></span>
          <span class="badge dark-badge ml-2"></span>
          <span class="color-label">DARK MODE</span>
        </li>
        
      </ul>

      <br />
    </div>
  </div>
  

unscript/templates/includes/navigation.html
<!-- Static assets -->
{% load static %}

      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-absolute navbar-transparent">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-toggle d-inline">
              <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </button>
            </div>
            <a class="navbar-brand" href="{% url 'mercuri:Dashboard' %}"><img src="{% static 'assets/img/logo.png' %}" style="height:30px" alt="Profile Photo">Mercuri Hospital </a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
          </button>
          <div class="collapse navbar-collapse" id="navigation">

            {% if user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
              <li class="dropdown nav-item">
                <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                  
                </a>
              </li>
              <li class="separator d-lg-none"></li>
            </ul>
            {% endif %}

          </div>
        </div>
      </nav>
      <div class="modal modal-search fade" id="searchModal" tabindex="-1" role="dialog" aria-labelledby="searchModal" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="SEARCH">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <i class="tim-icons icon-simple-remove"></i>
              </button>
            </div>
          </div>
        </div>
      </div>
      <!-- End Navbar -->

unscript/templates/includes/scripts-sidebar.html
  <script>
    $(document).ready(function() {
      $().ready(function() {
        $sidebar = $('.sidebar');
        $navbar = $('.navbar');
        $main_panel = $('.main-panel');

        $full_page = $('.full-page');

        $sidebar_responsive = $('body > .navbar-collapse');
        sidebar_mini_active = true;
        white_color = false;

        window_width = $(window).width();

        fixed_plugin_open = $('.sidebar .sidebar-wrapper .nav li.active a p').html();



        $('.fixed-plugin a').click(function(event) {
          if ($(this).hasClass('switch-trigger')) {
            if (event.stopPropagation) {
              event.stopPropagation();
            } else if (window.event) {
              window.event.cancelBubble = true;
            }
          }
        });

        $('.fixed-plugin .background-color span').click(function() {
          $(this).siblings().removeClass('active');
          $(this).addClass('active');

          var new_color = $(this).data('color');

          if ($sidebar.length != 0) {
            $sidebar.attr('data', new_color);
          }

          if ($main_panel.length != 0) {
            $main_panel.attr('data', new_color);
          }

          if ($full_page.length != 0) {
            $full_page.attr('filter-color', new_color);
          }

          if ($sidebar_responsive.length != 0) {
            $sidebar_responsive.attr('data', new_color);
          }
        });

        $('.switch-sidebar-mini input').on("switchChange.bootstrapSwitch", function() {
          var $btn = $(this);

          if (sidebar_mini_active == true) {
            $('body').removeClass('sidebar-mini');
            sidebar_mini_active = false;
            blackDashboard.showSidebarMessage('Sidebar mini deactivated...');
          } else {
            $('body').addClass('sidebar-mini');
            sidebar_mini_active = true;
            blackDashboard.showSidebarMessage('Sidebar mini activated...');
          }

          // we simulate the window Resize so the charts will get updated in realtime.
          var simulateWindowResize = setInterval(function() {
            window.dispatchEvent(new Event('resize'));
          }, 180);

          // we stop the simulation of Window Resize after the animations are completed
          setTimeout(function() {
            clearInterval(simulateWindowResize);
          }, 1000);
        });

        $('.switch-change-color input').on("switchChange.bootstrapSwitch", function() {
          var $btn = $(this);

          if (white_color == true) {

            $('body').addClass('change-background');
            setTimeout(function() {
              $('body').removeClass('change-background');
              $('body').removeClass('white-content');
            }, 900);
            white_color = false;
          } else {

            $('body').addClass('change-background');
            setTimeout(function() {
              $('body').removeClass('change-background');
              $('body').addClass('white-content');
            }, 900);

            white_color = true;
          }


        });

        $('.light-badge').click(function() {
          $('body').addClass('white-content');
        });

        $('.dark-badge').click(function() {
          $('body').removeClass('white-content');
        });
      });
    });
  </script>
  

unscript/templates/includes/scripts.html
<!-- Static assets -->
{% load static %}

  <!--   Core JS Files   -->
  <script src="{% static 'assets/js/core/jquery.min.js' %}"></script>
  <script src="{% static 'assets/js/core/popper.min.js' %}"></script>
  <script src="{% static 'assets/js/core/bootstrap.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins/perfect-scrollbar.jquery.min.js' %}"></script>
  <!--  Google Maps Plugin    -->
  <!-- Place this tag in your head or just before your close body tag. -->
  <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
  <!-- Chart JS -->
  <script src="{% static 'assets/js/plugins/chartjs.min.js' %}"></script>
  <!--  Notifications Plugin    -->
  <script src="{% static 'assets/js/plugins/bootstrap-notify.js' %}"></script>
  <!-- Control Center for Black Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{% static 'assets/js/black-dashboard.min.js' %}"></script><!-- Black Dashboard DEMO methods, don't include it in your project! -->
  <script src="{% static 'assets/demo/demo.js' %}"></script>

unscript/templates/includes/sidebar.html
 <div class="sidebar">
      <div class="sidebar-wrapper">
        
        <div class="logo">
          <a 
             href="{% url 'mercuri:Dashboard' %}" class="simple-text logo-normal">
             Mercury Dashboard
          </a>
        </div>


        {% if user.is_authenticated %}
        <ul class="nav">
          <li>
            <a href="{% url 'mercuri:Dashboard' %}">
              <i class="tim-icons icon-chart-pie-36"></i>
              <p>Dashboard</p>
            </a>
          </li>
          <li>
            <a href="{% url 'mercuri:searchPatient' %}">
              <i class="tim-icons icon-single-02"></i>
              <p>Search Patient</p>
            </a>
          </li>
          <li>
            <a href="{% url 'mercuri:listPatients' %}">
              <i class="tim-icons icon-puzzle-10"></i>
              <p>Patients List</p>
            </a>
          </li>
          <li>
            <a href="{% url 'mercuri:modifyHospital' %}">
              <i class="tim-icons icon-single-02"></i>
              <p>Update Hospital Data</p>
            </a>
          </li>

          <li>
            <a href="{% url 'mercuri:addDoctor' %}">
              <i class="tim-icons icon-single-02"></i>
              <p>Add Doctor</p>
            </a>
          </li>

          <li>
            <a href="{% url 'mercuri:addStaff' %}">
              <i class="tim-icons icon-single-02"></i>
              <p>Add Staff</p>
            </a>
          </li>

          <li>
            <a href="{% url 'mercuri:addReception' %}">
              <i class="tim-icons icon-single-02"></i>
              <p>Add Reception</p>
            </a>
          </li>

          <li>
            <a href="{% url 'mercuri:addPatient' %}">
              <i class="tim-icons icon-single-02"></i>
              <p>Add Patient</p>
            </a>
          </li>
          <li>
            <a href="{% url 'mercuri:InstanceStatus' %}">
              <i class="tim-icons icon-puzzle-10"></i>
              <p>Instance Status</p>
            </a>
          </li>

          <li>
            <a href="{% url 'mercuri:addHospital' %}">
              <i class="tim-icons icon-single-02"></i>
              <p>Add Hospital Data</p>
            </a>
          </li>

          <li>
            <a href="{% url 'logout' %}">
              <i class="tim-icons icon-single-02"></i>
              <p>Logout</p>
            </a>
          </li>
        </ul>
        {% endif %}
        
      </div>
    </div>