unscript/mercuri/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name='mercuri'

urlpatterns = [
    path('addPatient', views.addPatient.as_view(), name="addPatient"),
    path('addDoctor', views.addDoctor.as_view(), name="addDoctor"),
    path('addStaff', views.addStaff.as_view(), name="addStaff"),
    path('addReception', views.addReception.as_view(), name="addReception"),
    path('modifyPatient/<str:mail>', views.modifyPatient.as_view(), name="modifyPatient"),
    path('addHospital', views.addHospital.as_view(), name="addHospital"),
    path('InstanceStatus', views.InstanceStatus.as_view(), name="InstanceStatus"),
    path('Dashboard', views.Dashboard.as_view(), name="Dashboard"),
    path('listPatients', views.listPatients.as_view(), name="listPatients"),
    path('modifyHospital', views.modifyHospital.as_view(), name="modifyHospital"),
    path('addHospital', views.addHospital.as_view(), name="addHospital"),
    path('searchPatient', views.searchPatient.as_view(), name="searchPatient"),
]

unscript/unscript/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Login.as_view(), name="login"),
    path('mercuri',include('mercuri.urls')),
    path('logout', views.logout_user, name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

unscript/templates/addDoctor.html
{% extends 'layouts/base.html' %}

{% block title %} Page User {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <h4 class="title">Doctor Registration</h4>
      </div>
      <br><p>{{error_message}}<br>
      <div class="card-body">
        <form role="form" method="post" action="">
            {% csrf_token %} 

          <div class="row">
            <div class="col-md-6 pr-md-1">
              <div class="form-group">
                <label for="fName">First Name:</label>
                <input type="text" name="fName" class="form-control" required>
              </div>
            </div>
            <div class="col-md-6 pl-md-1">
              <div class="form-group">
                <label for="lName">Last Name:</label>
                <input type="text" name="lName" class="form-control" required>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-6 pr-md-1">
              <div class="form-group">
                <label for="email">Email:</label>
                <input type="text" name="email" class="form-control" required>
              </div>
            </div>
          </div>
        
          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <label for="address">Address:</label>
                <input type="text" name="address" class="form-control" placeholder="Home Address" required>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-6 pr-md-1">
              <div class="form-group">
                <label for="title">Title: </label>
                <input type="text" class="form-control" name="title" required>
              </div>
            </div>
            <div class="col-md-6 pl-md-1">
              <div class="form-group">
                <label for="contactNo"> Contact Number: </label>    
                  <input type="text" name="contactNo" class="form-control" size="10" required>
              </div>
            </div> 
          </div>

          <div class="row">
            <div class="col-md-6 pr-md-1">
              <div class="form-group">
                <label for="doctorID">Doctor ID: </label>
                <input type="text" class="form-control" name="doctorID" required>
              </div>
            </div>
            <div class="col-md-6 pl-md-1" class="form-control">
              <div class="form-group">
                <label for="shift"> Shift: </label>   
                
                <select name="shift" class="form-control">
                    <option value="Morning" style="background-color: #1d253b">Morning</option>
                    <option value="Afternoon" style="background-color: #1d253b">Afternoon</option>
                    <option value="Night" style="background-color: #1d253b">Night</option>
                </select>
              </div>
            </div> 
          </div>

         <div class="row">
            <div class="col-md-6 pr-md-1">
              <div class="form-group">
                <label for="password">Password: </label>
                <input type="password" class="form-control" name="password" required>
              </div>
            </div>
            <div class="col-md-6 pl-md-1">
              <div class="form-group">
                <label for="confPassword"> Confirm Password: </label>    
                  <input type="password" name="confPassword" class="form-control" required>
              </div>
            </div> 
          </div>
            

          <div class="card-footer">
              <button type="submit" class="btn btn-fill btn-primary">Add Doctor</button>
          </div>
        </form>
      </div>
      
    </div>
  </div>


  
  </div>
</div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

unscript/templates/addPatient.html
{% extends 'layouts/base.html' %}

{% block title %} Page User {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <h4 class="title">Patient Registration</h4>
      </div>
      <br><p>{{error_message}}<br>
      <div class="card-body">
        <form role="form" method="post" action="">
            {% csrf_token %} 

          <div class="row">
            <div class="col-md-6 pr-md-1">
              <div class="form-group">
                <label for="fName">First Name:</label>
                <input type="text" name="fName" class="form-control" required>
              </div>
            </div>
            <div class="col-md-6 pl-md-1">
              <div class="form-group">
                <label for="lName">Last Name:</label>
                <input type="text" name="lName" class="form-control" required>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-6 pr-md-1">
              <div class="form-group">
                <label for="email">Email:</label>
                <input type="text" name="email" class="form-control" required>
              </div>
            </div>
          </div>
        
          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <label for="address">Address:</label>
                <input type="text" name="address" class="form-control" placeholder="Home Address" required>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-6 pr-md-1">
              <div class="form-group">
                <label for="age">Age: </label>
                <input type="text" class="form-control" name="age" required>
              </div>
            </div>
            <div class="col-md-6 pl-md-1">
              <div class="form-group">
                <label for="contactNo"> Contact Number: </label>    
                  <input type="text" name="contactNo" class="form-control" size="10" required>
              </div>
            </div> 
          </div>

          <div class="row">
            <div class="col-md-6 pr-md-1">
              <div class="form-group">
                <label for="patientID">Patient ID: </label>
                <input type="text" class="form-control" name="patientID" required>
              </div>
            </div>
            <div class="col-md-6 pl-md-1">
              <div class="form-group">
                <label for="operatedByDoctor"> Operated By Doctor: </label>    
                  <input type="text" name="operatedByDoctor"class="form-control" required>
              </div>
            </div> 
          </div>

          <div class="row">
            <div class="col-md-6 pr-md-1">
              <div class="form-group">
                <label for="remarks">Report: </label>
                <textarea rows="4" cols="100"class="form-control" name="remarks" required></textarea>
              </div>
            </div>
            <div class="col-md-6 pl-md-1">
              <div class="form-group">
                <label for="medicalHistory"> Medical History: </label>    
                <textarea rows="4" cols="100"class="form-control" name="medicalHistory" required></textarea>
              </div>
            </div> 
          </div>

          <div class="card-footer">
              <button type="submit" class="btn btn-fill btn-primary">Add Patient</button>
          </div>
        </form>
      </div>
      
    </div>
  </div>


  
  </div>
</div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

unscript/templates/addReception.html
{% extends 'layouts/base.html' %}

{% block title %} Page User {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}


<div >
  <div class="card card-user">
    <div class="card-body">
      <p class="card-text">
        <div class="author">
          <div class="block block-one"></div>
          <div class="block block-two"></div>
          <div class="block block-three"></div>
          <div class="block block-four"></div>
          <a href="javascript:void(0)">
            <img class="avatar" src="/static/assets/img/emilyz.jpg" alt="...">
            <h5 class="title">
              {{ request.user.username }}
            </h5>
          </a>
          <p class="description">
            {{ request.user.email }}
          </p>
        </div>
      </p>
    </div>
  </div>
</div>

<form class="" action="" method="post">
{% csrf_token %}
  <div >
    <div >
      <div class="card">
        <div class="card-header">
          <h5 class="title">Add Reception</h5>
        </div>
        <br> <p>{{error_message}}</p> <br>
        <div class="card-body">
          <form>

            <div class="row">

              <div class="col-md-5 pr-md-1">
                <div class="form-group">
                  <label>First Name</label>
                  <input type="text" class="form-control"  name="fName">
                </div>
              </div>

              <div class="col-md-5 pr-md-1">
                <div class="form-group">
                  <label>Last Name</label>
                  <input type="text" class="form-control"  name="lName">
                </div>
              </div>

            </div>


            <div class="row">

              <div class="col-md-5 pr-md-1">
                <div class="form-group">
                  <label for="exampleInputEmail1">Email address</label>
                  <input type="email" class="form-control" name="email">
                </div>
              </div>

              <div class="col-md-5 pr-md-1">
                <div class="form-group">
                  <label >Mobile No.</label>
                  <input type="number" class="form-control" name="contactNo">
                </div>
              </div>

            </div>

            <div class="row" style="padding-left:15px">

              <div class="col-md-5 pl-md-1">
                <div class="form-group">
                  <label>Staff ID</label>
                  <input type="text" class="form-control" name="staffID">
                </div>
              </div>

              <div class="dropdown">
                  <button style="margin-top:25% " class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Shift
                  </button>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <input type="radio" name="shift" value="Morning" style="margin-left:40px" >  Morning<br>
                    <input type="radio" name="shift" value="Evening" style="margin-left:40px">  Evening<br>
                    <input type="radio" name="shift" value="Night" style="margin-left:40px">  Night
              </div>
            </div>

            </div>

            <div class="col-md-4 pl-md-1 " style="padding-left:0">

            </div>

            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label>Address</label>
                  <input type="text" class="form-control" placeholder="Home Address" name="address">
                </div>
              </div>
            </div>
            <div class="row">

              <div class="col-md-5 pr-md-1">
                <div class="form-group">
                  <label for="password">Password</label>
                  <input type="password" class="form-control" name="password">
                </div>
              </div>

              <div class="col-md-5 pr-md-1">
                <div class="form-group">
                  <label for="confPassword">Confirm Password</label>
                  <input type="password" class="form-control" name="confPassword">
                </div>
              </div>

            </div>

            <div class="card-footer">
              <button type="submit" name="submit" class="btn btn-fill btn-primary">Save</button>
            </div>
          </form>
        </div>

      </div>
    </div>

  </div>

</form>



{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

unscript/templates/index.html
{% extends "layouts/base.html" %}

{% block title %} Dashboard {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

 <!-- graph 1 --> 
    <div class="row">
      <div class="col-12">
        <div class="card card-chart">
          <div class="card-header ">
            <div class="row">
              <div class="col-sm-6 text-left">
                <h5 class="card-category">COVID 19 Overview </h5>
                <h2 class="card-title" id = "tot">Active Patients</h2>
              </div>
              <div class="col-sm-6">
                <div class="btn-group btn-group-toggle float-right" data-toggle="buttons">
                  <label class="btn btn-sm btn-primary btn-simple active" id="0">
                    <input type="radio" name="options" checked>
                    <span class="d-none d-sm-block d-md-block d-lg-block d-xl-block" onclick="active()">Active</span>
                    <span class="d-block d-sm-none">
                      <i class="tim-icons icon-single-02"></i>
                    </span>
                  </label>
                  <label class="btn btn-sm btn-primary btn-simple" id="1">
                    <input type="radio" class="d-none d-sm-none" name="options">
                    <span class="d-none d-sm-block d-md-block d-lg-block d-xl-block" onclick="recovered()">Recovered</span>
                    <span class="d-block d-sm-none">
                      <i class="tim-icons icon-gift-2"></i>
                    </span>
                  </label>
                  <label class="btn btn-sm btn-primary btn-simple" id="2">
                    <input type="radio" class="d-none" name="options">
                    <span class="d-none d-sm-block d-md-block d-lg-block d-xl-block " onclick="Deceased()">Deceased</span>
                    <span class="d-block d-sm-none">
                      <i class="tim-icons icon-tap-02"></i>
                    </span>
                  </label>
                </div>
              </div>
            </div>
          </div>
          <div class="card-body">
            <div class="chart-area">
              <canvas id="chartBig1"></canvas>
            </div>
          </div>
        </div>
      </div>
    </div>

<p id="act" hidden>{{act}}</p>
<p id="rec" hidden>{{rec}}</p>
<p id="dec" hidden>{{dec}}</p>
<p id = "totVents" hidden>{{totVents}}</p>
<p id = "occVents" hidden>{{occVents}}</p>
<p id = "availVents" hidden>{{availVents}}</p>
<p id = "totBeds" hidden>{{totBeds}}</p>
<p id = "occBeds" hidden>{{occBeds}}</p>
<p id = "availBeds" hidden>{{availBeds}}</p>
<p id="active"></p>
<p id="dece"></p>
<p id="reco"></p>

    <!-- graph 1 end -->

    <!-- graph 2 -->

    <div class="row">
      <div class="col-lg-6">
        <div class="card card-chart">
          <div class="card-header">

            <div class ="row">
              <div class="pr-md-2" style="padding-left: 4%;">
                <h4 class="card-category">Total Beds</h4>
                <h3 class="card-title"><i class="tim-icons icon-send text-success"></i>{{totBeds}}</h3>
              </div>
              <div style="padding-left: 2%;
                  border-left: 2px solid green;
                  height: 60px;">
              </div>

              <div class="pr-md-2" style="padding-left: 2%;">
                <h4 class="card-category">Occupied Beds</h4>
                <h3 class="card-title"><i class="tim-icons icon-send text-success"></i>{{occBeds}}</h3>
              </div>
              
              <div style="padding-left: 2%;
                  border-left: 2px solid green;
                  height: 60px;">
              
               </div>
              
              <div class="pr-md-2" style="padding-left: 4%;">
                <h4 class="card-category">Available Beds</h4>
                <h3 class="card-title"><i class="tim-icons icon-send text-success"></i>{{availBeds}}</h3>
              </div> 

            </div>          
          </div>
          <div class="card-body">
            <div class="chart-area">
              <canvas id="chartLinePurple"></canvas>
            </div>
          </div>
        </div>
      </div>
      
      <div class="col-lg-6">
        <div class="card card-chart">
          <div class="card-header">
            <div class ="row">
              <div class="pr-md-2" style="padding-left: 4%;">
                <h5 class="card-category">Total Ventilators</h5>
                <h3 class="card-title"><i class="tim-icons icon-send text-success"></i>{{totVents}}</h3>
              </div>

              <div style="padding-left: 2%;
                  border-left: 2px solid green;
                  height: 60px;">
              </div>
              
              <div class="pr-md-2" style="padding-left: 4%;"><h5 class="card-category">Occupied Ventilators</h5>
                <h3 class="card-title"><i class="tim-icons icon-send text-success"></i>{{occVents}}</h3>
              </div>
              
              <div style="padding-left: 2%;
                  border-left: 2px solid green;
                  height: 60px;">
              </div>
              
              <div class="pr-md-2" style="padding-left: 4%;"><h5 class="card-category">Available Ventilators</h5>
                <h3 class="card-title"><i class="tim-icons icon-send text-success"></i>{{availVents}}</h3>
              </div>        
            </div>
          </div>
          <div class="card-body">
            <div class="chart-area">
              <canvas id="chartLineGreen"></canvas>
            </div>
          </div>
        </div>
      </div>
    </div>


<!-- graph 3 end -->

<!-- removed unwanted part -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

<script>
  function recovered() {
    document.getElementById("tot").innerHTML = "Recovery Rate";
    
  }

  function active() {
    document.getElementById("tot").innerHTML = "Active Patients";
    
  }

  function Deceased() {
    document.getElementById("tot").innerHTML = "Death Rate";
    
  }
  </script>
  <script>
    $(document).ready(function() {
      // Javascript method's body can be found in assets/js/demos.js
      demo.initDashboardPageCharts();

    });
  </script>

{% endblock javascripts %}

unscript/templates/modifyHospital.html
{% extends "layouts/base.html" %}

{% block title %} Hospital Data {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

        <div class="row">
          <div class="col-md-8">
            <div class="card">

              <form role="form" method="post" action="">
              
                {% csrf_token %} 

                <div class="card-header">
                  <h5 class="title">Modify Hospital</h5>

                  <h6 class="card-category">
                      {% if errorMessage %}
                        <span class="text-danger">{{ errorMessage }}</span>
                      {% endif %}  
                  </h6>
                </div>
                <div class="card-body">

                    <div class="row">
                      <div class="col-md-3 px-md-1">
                        <div class="form-group">
                          <label for="name">Name</label>
                          <input type="text" name="name" id="name" value="{{hos.name}}" disabled>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-3 px-md-1">
                        <div class="form-group">
                          <label for="address">Address</label>
                          <input type="text" name="address" id="address" value="{{hos.address}}" disabled>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-3 px-md-1">
                        <div class="form-group">
                          <label for="contactNo">Contact No</label>
                          <input type="text" name="contactNo" id="contactNo" value="{{hos.contactNo}}" disabled>
                        </div>
                      </div>
                    </div>
                    
                    <div class="row">
                        <div class="col-md-3 px-md-1">
                            <div class="form-group">
                            <label for="ventilators">Ventilators</label>
                            <input type="text" name="ventilators" id="ventilators" value="{{hos.ventilators}}">
                            </div>
                        </div>
                    </div>

                    <div class="row">
                      <div class="col-md-3 px-md-1">
                          <div class="form-group">
                          <label for="beds">Beds</label>
                          <input type="text" name="beds" id="beds" value="{{hos.beds}}">
                          </div>
                      </div>
                  </div>

              <div class="row">
                <div class="col-md-3 px-md-1">
                    <div class="form-group">
                    <label for="availableOxygenCylinders">Available Oxygen Cylinders</label>
                    <input type="text" name="availableOxygenCylinders" id="availableOxygenCylinders" value="{{hos.availableOxygenCylinders}}">
                    </div>
                </div>
            </div>

                </div>
                <div class="card-footer">
                  <button type="submit" class="btn btn-fill btn-primary">Modify Hospital</button>
                  &nbsp; &nbsp;
                </div>

              </form>

            </div>
          </div>
      </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

unscript/templates/page-blank.html
{% extends 'layouts/base.html' %}

{% block title %} Page Blank {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card card-profile">
                <div class="card-body">
                    <h6 class="card-category text-gray">Page Blank</h6>
                    <h4 class="card-title">
                        Add your content 
                    </h4>
                    <a href="/" class="btn btn-primary btn-round">Home</a>
                </div>
            </div>
        </div>
    </div>
    
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

unscript/templates/searchPatient.html
{% extends "layouts/base.html" %}

{% block title %} Hospital Data {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="row">
  <div class="col-md-8">
    <div class="card">

      <form role="form" method="post" action="">

        {% csrf_token %}
        <div class="card-header">
          <h5 class="title">Search Patient</h5>

          <h6 class="card-category">
            {% if errorMessage %}
            <span class="text-danger">{{ errorMessage }}</span>
            {% endif %}
          </h6>
        </div>
        <div class="card-body">
          <div class="col-md-6 pl-md-1" class="form-control">
            <div class="form-group">
              <label for="choice"> Query By: </label>
              <select name="choice" class="form-control" required>
                <option value="ID" style="background-color: #1d253b">ID</option>
                <option value="mail" style="background-color: #1d253b">E-Mail</option>
              </select>
            </div>
          </div>

          <div class="row">
            <div class="col-md-3 px-md-1">
              <div class="form-group" style="padding-left: 10%;">
                <label for="query">Query</label>
                <input type="text" name="query" id="query" required>
              </div>
            </div>
          </div>

        </div>
        <div class="card-footer">
          <button type="submit" class="btn btn-fill btn-primary">Search Patient</button>
          &nbsp; &nbsp;
        </div>


      </form>
      <br><br>
    </div>
  </div>
</div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

unscript/templates/searchResult.html
{% extends "layouts/base.html" %}

{% block title %} Search Result {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="row">
  <div class="col-md-8">
    <div class="card">
    <br>
    <h6 class="card-category">
            {% if errorMessage %}
            <span class="text-danger">{{ errorMessage }}</span>
            {% endif %}
          </h6>
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Status</th>
            <th scope="col">ID</th>
            <th scope="col">Operated By</th>
            <th scope="col">Email</th>
          </tr>
        </thead>
        <tbody>
            <tr>
              <th scope="row"><a href = "{% url 'mercuri:modifyPatient' i.email %}">{{i.fName}} {{i.lName}}</a></th>
              {% if i.currentStatus == 'Active' %}
              <td><span style="color: #fad60c;">{{i.currentStatus}}</span></td>
              {% elif i.currentStatus == 'Dead' %}
              <td><span style="color: #ff4141;">{{i.currentStatus}}</span></td>
              {% elif i.currentStatus == 'Recovered' %}
              <td><span style="color: #07ce00;">{{i.currentStatus}}</span></td>
              {% endif %}
              <td>{{i.patientID}}</td>
              <td>{{i.operatedByDoctor}}</td>
              <td>{{i.email}}</td>
            </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

unscript/templates/ui-maps.html
{% extends 'layouts/base.html' %}

{% block title %} Maps {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="row">
  <div class="col-md-12">
    <div class="card card-plain">
      <div class="card-header">
        Google Maps
      </div>
      <div class="card-body">
        <div id="map" class="map"></div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

<script>
  $(document).ready(function() {
    // Javascript method's body can be found in assets/js/demos.js
    demo.initGoogleMaps();
  });
</script>
  
{% endblock javascripts %}